// Generated by https://quicktype.io

export interface GetStudentsByInterestRequest {
  interestID: number;
}

export interface GetStudentsByInterestResponse {
  name:      string;
  last_name: string;
}
