// Generated by https://quicktype.io

import React, { useContext, useState } from "react";
import { LoginUserResponse } from "../../../Core/Entities/Service/Read/LoginUser";


export const UserContext = React.createContext<
  [
    LoginUserResponse | null,
    React.Dispatch<
      React.SetStateAction<
        LoginUserResponse | null
    >>
  ]>([null, () => null]);

const UserContextProvider = ({ children }: any) => {
  const [user, setUser] = useState<LoginUserResponse | null>(null);

  return (
    <UserContext.Provider value={[user, setUser]}>
      {children}
    </UserContext.Provider>
  );
}

export default UserContextProvider;