// Generated by https://quicktype.io

import React, { useContext, useState } from "react";
import { LoginUserResponse } from "../../../Core/Entities/Service/Read/LoginUser";

export type UserContextType = [
  LoginUserResponse | null,
  React.Dispatch<
    React.SetStateAction<
      LoginUserResponse | null
  >>
]

export const UserContext = React.createContext<
    UserContextType
  >([null, () => null]);

const UserContextProvider = ({ children }: any) => {
  const [user, setUser] = useState<LoginUserResponse | null>(null);

  return (
    <UserContext.Provider value={[user, setUser]}>
      {children}
    </UserContext.Provider>
  );
}

export default UserContextProvider;