// Generated by https://quicktype.io

export interface RegisterUserRequest {
  email:     string;
  password:  string;
  career:    string;
  on:        string;
  avatar:    Avatar;
  interests: Interest[];
  groups: Group[];
}

export interface RegisterUserResponse {
  id:         number;
  email:      string;
  password:   string;
  name:       string;
  lastName:   string;
  career:     string;
  status:     string;
  university: any;
  avatar:     Avatar;
  groups:     Group[];
  interests:  Interest[];
}

export interface Avatar {
  id?:        number;
  sexo:      string;
  hairStyle: string;
  skinColor: string;
  hairColor: string;
}

export interface Interest {
  id:   number;
  name: string;
}

export interface Group {
  id:           number;
  title:        string;
  description:  string;
  participants: any[];
}
