// Generated by https://quicktype.io

export interface RegisterUserRequest {
  email:     string;
  password:  string;
  career:    string;
  on:        string;
  avatar:    Avatar;
  interests: Interest[];
  groups: Group[];
}

export interface RegisterUserResponse {
  
}

export interface Avatar {
  sexo:      string;
  hairStyle: string;
  skinColor: string;
  hairColor: string;
}

export interface Interest {
  name: string;
}

export interface Group {
  title: string;
}