// Generated by https://quicktype.io

import React, { useContext, useState } from "react";
import PeopleEvent from "../../../Core/Entities/PeopleEvent";

export type EventsContextType = [
  PeopleEvent[],
  React.Dispatch<
    React.SetStateAction<
      PeopleEvent[]
  >>
]

export const EventsContext = React.createContext<
    EventsContextType
  >([[], () => []]);

const EventsContextProvider = ({ children }: any) => {
  const [events, setEvents] = useState<PeopleEvent[]>([]);

  return (
    <EventsContext.Provider value={[events, setEvents]}>
      {children}
    </EventsContext.Provider>
  );
}

export default EventsContextProvider;