// Generated by https://quicktype.io

import React, { useContext, useState } from "react";
import PeopleEvent from "../../../Core/Entities/PeopleEvent";


export const EventsContext = React.createContext<
  [
    PeopleEvent[],
    React.Dispatch<
      React.SetStateAction<
        PeopleEvent[]
    >>
  ]>([[], () => []]);

const EventsContextProvider = ({ children }: any) => {
  const [events, setEvents] = useState<PeopleEvent[]>([]);

  return (
    <EventsContext.Provider value={[events, setEvents]}>
      {children}
    </EventsContext.Provider>
  );
}

export default EventsContextProvider;